export type Monster = (typeof monsters)[number];

export type Dungeon = (typeof dungeons)[number];

export type SlayerTier = (typeof slayerTiers)[number];

export const slayerTiers = [
  {
    name: "Easy",
    monsters: [
      "Black Knight",
      "Hill Giant",
      "Giant Crab",
      "Tentacle",
      "Seagull",
      "Confused Pirate",
      "Frozen Archer",
      "Wet Monster",
      "Moist Monster",
      "Sweaty Monster",
      "Golbin",
      "Ranged Golbin",
      "Chicken",
      "Cow",
      "Zombie Hand",
      "Zombie",
      "Ghost",
      "Junior Farmer",
      "Adult Farmer",
      "Master Farmer",
      "Wizard",
      "Steel Knight",
      "Mithril Knight",
      "Bandit Trainee",
      "Bandit",
      "Skeleton",
      "Leech",
      "Plant",
      "Mummy",
      "Statue",
      "Many Eyed Monster",
      "Lots of Eyes",
      "Fairy",
      "Goo Monster",
      "Green Goo Monster",
    ],
  },
  {
    name: "Normal",
    monsters: [
      "Moss Giant",
      "Frozen Mammoth",
      "Ice Monster",
      "Green Dragon",
      "Blue Dragon",
      "Adamant Knight",
      "Master Wizard",
      "Elerine Archer",
      "Elerine Warrior",
      "Stone Snake",
      "Undead Werewolf",
      "Vampire",
      "Strange Eyed Monster",
      "Eyes",
      "Valkyrie",
      "Angel",
      "Holy Archer",
      "Purple Goo Monster",
      "Scattered Goo Monster",
      "Druid",
      "Thief",
      "Shaman",
      "Turkul Riders",
      "Turkul Archers",
      "Turkul Throwers",
      "Wandering Bard",
    ],
  },
  {
    name: "Hard",
    monsters: [
      "Red Dragon",
      "Black Dragon",
      "Rune Knight",
      "Dark Wizard",
      "Elerine Mage",
      "Fierce Devil",
      "Griffin",
      "Pegasus",
      "Raging Horned Elite",
      "Seething Horned Elite",
      "Necromancer",
      "Elementalist",
      "Turkul Giant",
      "Turkul General",
      "Sand Beast",
      "Paladin",
      "Priest",
      "Superior Eyed Monster",
    ],
  },
  {
    name: "Elite",
    monsters: [
      "Dark Horned Elite",
      "Furious Horned Elite",
      "Rancora Spider",
      "Elder Vampire",
      "Cursed Maiden",
      "Bounty Hunter",
      "Eye of Fear",
      "Noxious Serpent",
      "Venomous Snake",
      "Giant Moth",
      "Hungry Plant",
    ],
  },
  {
    name: "Master",
    monsters: [
      "Chaotic Greater Dragon",
      "Hunting Greater Dragon",
      "Wicked Greater Dragon",
      "Umbora",
      "Rokken",
      "Ku-tul",
      "Legaran Wurm",
      "Cursed Lich",
      "Spiked Red Claw",
      "Greater Skeletal Dragon",
      "Poison Toad",
      "Kongamato",
      "Conda",
      "Alraune",
      "Burning Snake",
      "Infernal Golem",
      "Magic Fire Demon",
      "Frost Golem",
      "Siren",
    ],
  },
  {
    name: "Legendary",
    monsters: [
      "Manticore",
      "Gret-Yun",
      "Large Ice Troll",
      "Polar Bear",
      "Spectral Ice Wolf",
      "Monster Croc",
      "Leviathan",
      "Shadow Beast",
      "Plague Doctor",
      "Cockatrice",
      "Goliath Werewolf",
      "Phantom",
      "Banshee",
      "Spectre",
    ],
  },
  {
    name: "Mythical",
    monsters: [
      "Ice Hydra",
      "Twin Sea Dragon Serpent",
      "Torvair",
      "Arctair",
      "Harkair",
      "Vorloran Devastator",
      "Vorloran Watcher",
      "Vorloran Protector",
      "Guardian of the Herald",
    ],
  },
] as const;

export const dungeons = [
  { name: "Chicken Coop", monsters: ["Chicken", "Chick", "Mumma Chicken"] },
  {
    name: "Undead Graveyard",
    monsters: ["Zombie Hand", "Zombie", "Ghost", "Zombie Leader"],
  },
  {
    name: "Bandit Base",
    monsters: ["Bandit Trainee", "Bandit", "Bandit Leader"],
  },
  {
    name: "Hall of Wizards",
    monsters: ["Wizard", "Master Wizard", "Dark Wizard", "Elder Wizard"],
  },
  {
    name: "Spider Forest",
    monsters: ["Spider", "Brown Spider", "Evil Spider", "Spider King"],
  },
  {
    name: "Miolite Caves",
    monsters: [
      "Miolite Sprig",
      "Miolite Trio",
      "Miolite Warden",
      "Miolite Monarch",
    ],
  },
  {
    name: "Deep Sea Ship",
    monsters: ["Pirate", "First Mate", "Pirate Captain", "The Kraken"],
  },
  {
    name: "Frozen Cove",
    monsters: ["Ice Monster", "Ice Troll", "Ice", "Protector of Ice"],
  },
  {
    name: "Dragons Den",
    monsters: [
      "Green Dragon",
      "Blue Dragon",
      "Red Dragon",
      "Black Dragon",
      "Elder Dragon",
    ],
  },
  {
    name: "Volcanic Cave",
    monsters: [
      "Bat",
      "Big Bat",
      "The Eye",
      "Resurrected Eye",
      "Vicious Serpent",
      "Fire Spirit",
      "Prat, the Protector of Secrets",
      "Malcs, the Guardian of Melvor",
    ],
  },
  {
    name: "Infernal Stronghold",
    monsters: [
      "Cerberus",
      "Fearful Eye",
      "Red Devil",
      "Phoenix",
      "Incendius",
      "Prat, the Guardian of Secrets",
      "Malcs, the Leader of Dragons",
    ],
  },
  {
    name: "Air God Dungeon",
    monsters: [
      "Air Guard",
      "Air Monster",
      "Air Golem",
      "Aleron",
      "Voltaire",
      "Aeris",
    ],
  },
  {
    name: "Water God Dungeon",
    monsters: [
      "Water Guard",
      "Water Monster",
      "Water Golem",
      "Lissia",
      "Murtia",
      "Glacia",
    ],
  },
  {
    name: "Earth God Dungeon",
    monsters: [
      "Earth Guard",
      "Earth Monster",
      "Earth Golem",
      "Mistral",
      "Ophidia",
      "Terran",
    ],
  },
  {
    name: "Fire God Dungeon",
    monsters: [
      "Fire Guard",
      "Fire Monster",
      "Fire Golem",
      "Pyra",
      "Ignis",
      "Ragnar",
    ],
  },
  {
    name: "Ancient Sanctuary",
    monsters: [
      "Hungry Plant",
      "Poison Toad",
      "Kongamato",
      "Conda",
      "Alraune",
      "Morellia",
    ],
  },
  {
    name: "Underground Lava Lake",
    monsters: [
      "Burning Snake",
      "Infernal Golem",
      "Magic Fire Demon",
      "Manticore",
      "Gret-Yun",
      "Trogark",
    ],
  },
  {
    name: "Lightning Region",
    monsters: [
      "Lightning Spirit",
      "Lightning Monkey",
      "Lightning Golem",
      "RaZu, Lord of the Skies",
    ],
  },
  {
    name: "Lair of the Spider Queen",
    monsters: [
      "Scouter Spider",
      "Trapper Spider",
      "Wicked Spider",
      "Basher Spider",
      "Enforcer Spider",
      "Guardian Spider",
    ],
  },
  {
    name: "Cursed Forest",
    monsters: ["Tree Giant", "Tree Spirit", "Cursed Spirit", "Lady Darkheart"],
  },
  {
    name: "Necromancers Palace",
    monsters: [
      "Cursed Skeleton Warrior",
      "Bel-Noth",
      "Dark Knight",
      "Fiozor, the Ancient Necromancer",
    ],
  },
] as const;

export const monsters = [
  {
    name: "Chicken",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 1,
    attackBonus: -42,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:Chicken",
    areas: ["Farmlands", "Chicken Coop"],
  },
  {
    name: "Chick",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 1,
    attackBonus: -45,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:Chick",
    areas: ["Chicken Coop"],
  },
  {
    name: "Plant",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 1,
    attackBonus: -42,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:Plant",
    areas: ["Farmlands"],
  },
  {
    name: "Seagull",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 1,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:Seagull",
    areas: ["Sandy Shores"],
  },
  {
    name: "Golbin",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 1,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:Golbin",
    areas: ["Golbin Village"],
  },
  {
    name: "Cow",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 1,
    attackBonus: -15,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:Cow",
    areas: ["Farmlands"],
  },
  {
    name: "Junior Farmer",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 5,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:JuniorFarmer",
    areas: ["Farmlands"],
  },
  {
    name: "Ranged Golbin",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 5,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:RangedGolbin",
    areas: ["Golbin Village"],
  },
  {
    name: "Skeleton",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 10,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:Skeleton",
    areas: ["Graveyard"],
  },
  {
    name: "Steel Knight",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 10,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:SteelKnight",
    areas: ["Castle of Kings"],
  },
  {
    name: "Tentacle",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 10,
    attackBonus: 5,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:Tentacle",
    areas: ["Sandy Shores"],
  },
  {
    name: "Goo Monster",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 12,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:GooMonster",
    areas: ["Forest of Goo"],
  },
  {
    name: "Leech",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 20,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:Leech",
    areas: ["Wet Forest"],
  },
  {
    name: "Bat",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 30,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:Bat",
    areas: ["Volcanic Cave"],
  },
  {
    name: "Black Knight",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 20,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:BlackKnight",
    areas: ["Castle of Kings"],
  },
  {
    name: "Zombie Hand",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 20,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:ZombieHand",
    areas: ["Graveyard", "Undead Graveyard"],
  },
  {
    name: "Adult Farmer",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 20,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:AdultFarmer",
    areas: ["Farmlands"],
  },
  {
    name: "Bandit Trainee",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 20,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:BanditTrainee",
    areas: ["Bandit Hideout", "Bandit Base"],
  },
  {
    name: "Frozen Archer",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 40,
    attackBonus: 15,
    specialAttack: [
      { name: "Frostburn", maxHitMultiplier: 100, fixedAttack: false },
    ],
    intimidation: 0,
    id: "melvorD:FrozenArcher",
    areas: ["Icy Hills"],
  },
  {
    name: "Sweaty Monster",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 24,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:SweatyMonster",
    areas: ["Wet Forest"],
  },
  {
    name: "Hill Giant",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 22,
    attackBonus: 16,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:HillGiant",
    areas: ["Giant Dungeon"],
  },
  {
    name: "Mummy",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 27,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:Mummy",
    areas: ["Penumbra"],
  },
  {
    name: "Wizard",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 40,
    attackBonus: -6,
    spellMaxHit: 10.5,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:Wizard",
    areas: ["Wizard Tower", "Hall of Wizards"],
  },
  {
    name: "Giant Crab",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 15,
    attackBonus: 10,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:GiantCrab",
    areas: ["Sandy Shores"],
  },
  {
    name: "Mithril Knight",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 30,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:MithrilKnight",
    areas: ["Castle of Kings"],
  },
  {
    name: "Confused Pirate",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 20,
    attackBonus: 8,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:ConfusedPirate",
    areas: ["Sandy Shores"],
  },
  {
    name: "Wet Monster",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 30,
    attackBonus: 31,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:WetMonster",
    areas: ["Wet Forest"],
  },
  {
    name: "Zombie",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 30,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:Zombie",
    areas: ["Graveyard", "Undead Graveyard"],
  },
  {
    name: "Moist Monster",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 20,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:MoistMonster",
    areas: ["Wet Forest"],
  },
  {
    name: "Green Goo Monster",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 20,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:GreenGooMonster",
    areas: ["Forest of Goo"],
  },
  {
    name: "Statue",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 37,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:Statue",
    areas: ["Penumbra"],
  },
  {
    name: "Mumma Chicken",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 30,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:MummaChicken",
    areas: ["Chicken Coop"],
  },
  {
    name: "Many Eyed Monster",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 50,
    attackBonus: 20,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:ManyEyedMonster",
    areas: ["Strange Cave"],
  },
  {
    name: "Bandit",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 60,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:Bandit",
    areas: ["Bandit Hideout", "Bandit Base"],
  },
  {
    name: "Fairy",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 50,
    attackBonus: 4,
    spellMaxHit: 13,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:Fairy",
    areas: ["Holy Isles"],
  },
  {
    name: "Big Bat",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 60,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:BigBat",
    areas: ["Volcanic Cave"],
  },
  {
    name: "Ghost",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 40,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:Ghost",
    areas: ["Graveyard", "Undead Graveyard"],
  },
  {
    name: "Lots of Eyes",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 46,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:LotsofEyes",
    areas: ["Strange Cave"],
  },
  {
    name: "Master Farmer",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 45,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:MasterFarmer",
    areas: ["Farmlands"],
  },
  {
    name: "Spider",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 50,
    attackBonus: 0,
    specialAttack: [
      { name: "Venom", maxHitMultiplier: 100, fixedAttack: false },
    ],
    intimidation: 0,
    id: "melvorD:Spider",
    areas: ["Spider Forest"],
  },
  {
    name: "Purple Goo Monster",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 42,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:PurpleGooMonster",
    areas: ["Forest of Goo"],
  },
  {
    name: "Brown Spider",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 50,
    attackBonus: 0,
    specialAttack: [
      { name: "Venom", maxHitMultiplier: 100, fixedAttack: false },
    ],
    intimidation: 0,
    id: "melvorD:BrownSpider",
    areas: ["Spider Forest"],
  },
  {
    name: "Miolite Sprig",
    attackStyle: "Melee",
    canStun: false,
    canSleep: true,
    usesNormalHit: true,
    attackLevel: 50,
    attackBonus: 0,
    specialAttack: [{ name: "Spores", maxHit: 15, fixedAttack: true }],
    intimidation: 0,
    id: "melvorF:MioliteSprig",
    areas: ["Miolite Caves"],
  },
  {
    name: "Master Wizard",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 75,
    attackBonus: -9,
    spellMaxHit: 13.5,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:MasterWizard",
    areas: ["Wizard Tower", "Hall of Wizards"],
  },
  {
    name: "Vampire",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 70,
    attackBonus: 10,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:Vampire",
    areas: ["Penumbra"],
  },
  {
    name: "Turkul Riders",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 60,
    attackBonus: 0,
    specialAttack: [
      { name: "Lesser Sandstorm", maxHitMultiplier: 100, fixedAttack: false },
    ],
    intimidation: 0,
    id: "melvorF:TurkulRiders",
    areas: ["Arid Plains"],
  },
  {
    name: "Frozen Mammoth",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 60,
    attackBonus: 50,
    specialAttack: [
      { name: "Frostburn", maxHitMultiplier: 100, fixedAttack: false },
    ],
    intimidation: 0,
    id: "melvorD:FrozenMammoth",
    areas: ["Icy Hills"],
  },
  {
    name: "Moss Giant",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 50,
    attackBonus: 50,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:MossGiant",
    areas: ["Giant Dungeon"],
  },
  {
    name: "Undead Werewolf",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 55,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:UndeadWerewolf",
    areas: ["Penumbra"],
  },
  {
    name: "Druid",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 85,
    attackBonus: 25,
    spellMaxHit: 4.5,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:Druid",
    areas: ["Runic Ruins"],
  },
  {
    name: "Pirate",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 50,
    attackBonus: 12,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:Pirate",
    areas: ["Deep Sea Ship"],
  },
  {
    name: "Stone Snake",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 75,
    attackBonus: -9,
    spellMaxHit: 9.5,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:StoneSnake",
    areas: ["Penumbra"],
  },
  {
    name: "Adamant Knight",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 60,
    attackBonus: 30,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:AdamantKnight",
    areas: ["Castle of Kings"],
  },
  {
    name: "Scattered Goo Monster",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 50,
    attackBonus: 30,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:ScatteredGooMonster",
    areas: ["Forest of Goo"],
  },
  {
    name: "Wandering Bard",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 70,
    attackBonus: -9,
    spellMaxHit: 9.5,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:WanderingBard",
    areas: [],
  },
  {
    name: "Zombie Leader",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 60,
    attackBonus: 20,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:ZombieLeader",
    areas: ["Undead Graveyard"],
  },
  {
    name: "Valkyrie",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 79,
    attackBonus: 10,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:Valkyrie",
    areas: ["Holy Isles"],
  },
  {
    name: "Angel",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 80,
    attackBonus: 12,
    spellMaxHit: 12,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:Angel",
    areas: ["Holy Isles"],
  },
  {
    name: "Elerine Archer",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 100,
    attackBonus: 0,
    specialAttack: [
      { name: "Fleetness", maxHitMultiplier: 100, fixedAttack: false },
    ],
    intimidation: 0,
    id: "melvorD:ElerineArcher",
    areas: ["Elerine Battlegrounds"],
  },
  {
    name: "Strange Eyed Monster",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 65,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:StrangeEyedMonster",
    areas: ["Strange Cave"],
  },
  {
    name: "Ice Monster",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 70,
    attackBonus: 0,
    specialAttack: [
      { name: "Frostburn", maxHitMultiplier: 100, fixedAttack: false },
    ],
    intimidation: 0,
    id: "melvorD:IceMonster",
    areas: ["Icy Hills", "Frozen Cove"],
  },
  {
    name: "Ice",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 80,
    attackBonus: 0,
    specialAttack: [
      { name: "Frostburn", maxHitMultiplier: 100, fixedAttack: false },
    ],
    intimidation: 0,
    id: "melvorD:Ice",
    areas: ["Frozen Cove"],
  },
  {
    name: "Green Dragon",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 68,
    attackBonus: 40,
    specialAttack: [
      { name: "Lesser Dragonbreath", maxHit: 3, fixedAttack: true },
    ],
    intimidation: 0,
    id: "melvorD:GreenDragon",
    areas: ["Dragon Valley", "Dragons Den"],
  },
  {
    name: "Holy Archer",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 80,
    attackBonus: 50,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:HolyArcher",
    areas: ["Holy Isles"],
  },
  {
    name: "Turkul Archers",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 90,
    attackBonus: 0,
    specialAttack: [
      { name: "Lesser Sandstorm", maxHitMultiplier: 100, fixedAttack: false },
    ],
    intimidation: 0,
    id: "melvorF:TurkulArchers",
    areas: ["Arid Plains"],
  },
  {
    name: "First Mate",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 65,
    attackBonus: 35,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:FirstMate",
    areas: ["Deep Sea Ship"],
  },
  {
    name: "Eyes",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 70,
    attackBonus: 25,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:Eyes",
    areas: ["Strange Cave"],
  },
  {
    name: "Thief",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 95,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:Thief",
    areas: ["Runic Ruins"],
  },
  {
    name: "Ice Troll",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 80,
    attackBonus: 0,
    specialAttack: [
      { name: "Frostburn", maxHitMultiplier: 100, fixedAttack: false },
    ],
    intimidation: 0,
    id: "melvorD:IceTroll",
    areas: ["Frozen Cove"],
  },
  {
    name: "The Eye",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 120,
    attackBonus: -8,
    spellMaxHit: 9.5,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:TheEye",
    areas: ["Volcanic Cave"],
  },
  {
    name: "Evil Spider",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 80,
    attackBonus: 0,
    specialAttack: [
      { name: "Venom", maxHitMultiplier: 100, fixedAttack: false },
    ],
    intimidation: 0,
    id: "melvorD:EvilSpider",
    areas: ["Spider Forest"],
  },
  {
    name: "Blue Dragon",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 75,
    attackBonus: 50,
    specialAttack: [
      { name: "Lesser Dragonbreath", maxHit: 3, fixedAttack: true },
    ],
    intimidation: 0,
    id: "melvorD:BlueDragon",
    areas: ["Dragon Valley", "Dragons Den"],
  },
  {
    name: "Shaman",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 110,
    attackBonus: -3,
    spellMaxHit: 9,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:Shaman",
    areas: ["Runic Ruins"],
  },
  {
    name: "Turkul Throwers",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 110,
    attackBonus: 0,
    specialAttack: [
      { name: "Lesser Sandstorm", maxHitMultiplier: 100, fixedAttack: false },
    ],
    intimidation: 0,
    id: "melvorF:TurkulThrowers",
    areas: ["Arid Plains"],
  },
  {
    name: "Elerine Warrior",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 100,
    attackBonus: 0,
    specialAttack: [
      { name: "Fleetness", maxHitMultiplier: 100, fixedAttack: false },
    ],
    intimidation: 0,
    id: "melvorD:ElerineWarrior",
    areas: ["Elerine Battlegrounds"],
  },
  {
    name: "Fierce Devil",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 90,
    attackBonus: 10,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:FierceDevil",
    areas: ["Penumbra"],
  },
  {
    name: "Rune Knight",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 90,
    attackBonus: 60,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:RuneKnight",
    areas: ["Castle of Kings"],
  },
  {
    name: "Miolite Trio",
    attackStyle: "Magic",
    canStun: false,
    canSleep: true,
    usesNormalHit: true,
    attackLevel: 130,
    attackBonus: 4,
    spellMaxHit: 7,
    specialAttack: [{ name: "Spores", maxHit: 15, fixedAttack: true }],
    intimidation: 0,
    id: "melvorF:MioliteTrio",
    areas: ["Miolite Caves"],
  },
  {
    name: "Pirate Captain",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 80,
    attackBonus: 50,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:PirateCaptain",
    areas: ["Deep Sea Ship"],
  },
  {
    name: "Elerine Mage",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 135,
    attackBonus: -18,
    spellMaxHit: 12,
    specialAttack: [
      { name: "Fleetness", maxHitMultiplier: 100, fixedAttack: false },
    ],
    intimidation: 0,
    id: "melvorD:ElerineMage",
    areas: ["Elerine Battlegrounds"],
  },
  {
    name: "Red Dragon",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 90,
    attackBonus: 60,
    specialAttack: [
      { name: "Lesser Dragonbreath", maxHit: 3, fixedAttack: true },
    ],
    intimidation: 0,
    id: "melvorD:RedDragon",
    areas: ["Dragon Valley", "Dragons Den"],
  },
  {
    name: "Dark Wizard",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 90,
    attackBonus: 7,
    spellMaxHit: 13.5,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:DarkWizard",
    areas: ["Wizard Tower", "Hall of Wizards"],
  },
  {
    name: "Necromancer",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 125,
    attackBonus: -24,
    spellMaxHit: 13,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:Necromancer",
    areas: ["Runic Ruins"],
  },
  {
    name: "Bandit Leader",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 130,
    attackBonus: 10,
    specialAttack: [
      { name: "Rapid Fire", maxHitMultiplier: 100, fixedAttack: false },
    ],
    intimidation: 0,
    id: "melvorD:BanditLeader",
    areas: ["Bandit Base"],
  },
  {
    name: "Black Dragon",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 100,
    attackBonus: 80,
    specialAttack: [
      { name: "Lesser Dragonbreath", maxHit: 3, fixedAttack: true },
    ],
    intimidation: 0,
    id: "melvorD:BlackDragon",
    areas: ["Dragon Valley", "Dragons Den"],
  },
  {
    name: "Elder Wizard",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 120,
    attackBonus: 0,
    spellMaxHit: 13,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:ElderWizard",
    areas: ["Hall of Wizards"],
  },
  {
    name: "Griffin",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 67,
    attackBonus: 30,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:Griffin",
    areas: ["High Lands"],
  },
  {
    name: "Miolite Warden",
    attackStyle: "Melee",
    canStun: false,
    canSleep: true,
    usesNormalHit: true,
    attackLevel: 130,
    attackBonus: 0,
    specialAttack: [{ name: "Spores", maxHit: 15, fixedAttack: true }],
    intimidation: 0,
    id: "melvorF:MioliteWarden",
    areas: ["Miolite Caves"],
  },
  {
    name: "Raging Horned Elite",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 79,
    attackBonus: 30,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:RagingHornedElite",
    areas: ["Desolate Plains"],
  },
  {
    name: "Turkul Giant",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 135,
    attackBonus: 15,
    specialAttack: [
      { name: "Lesser Sandstorm", maxHitMultiplier: 100, fixedAttack: false },
    ],
    intimidation: 0,
    id: "melvorF:TurkulGiant",
    areas: ["Arid Plains"],
  },
  {
    name: "Cerberus",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 140,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:Cerberus",
    areas: ["Infernal Stronghold"],
  },
  {
    name: "Paladin",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 110,
    attackBonus: 16,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:Paladin",
    areas: ["Holy Isles"],
  },
  {
    name: "Superior Eyed Monster",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 160,
    attackBonus: 35,
    spellMaxHit: 9,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:SuperiorEyedMonster",
    areas: ["Strange Cave"],
  },
  {
    name: "Priest",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 175,
    attackBonus: 8,
    spellMaxHit: 10.5,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:Priest",
    areas: ["Holy Isles"],
  },
  {
    name: "Spider King",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 120,
    attackBonus: 0,
    specialAttack: [
      { name: "Venom", maxHitMultiplier: 100, fixedAttack: false },
    ],
    intimidation: 0,
    id: "melvorD:SpiderKing",
    areas: ["Spider Forest"],
  },
  {
    name: "Seething Horned Elite",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 192,
    attackBonus: 3,
    spellMaxHit: 12,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:SeethingHornedElite",
    areas: ["Desolate Plains"],
  },
  {
    name: "Turkul General",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 180,
    attackBonus: 0,
    specialAttack: [
      { name: "Lesser Sandstorm", maxHitMultiplier: 100, fixedAttack: false },
    ],
    intimidation: 0,
    id: "melvorF:TurkulGeneral",
    areas: ["Arid Plains"],
  },
  {
    name: "Air Guard",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 200,
    attackBonus: 35,
    specialAttack: [{ name: "Barrage", maxHit: 10, fixedAttack: true }],
    intimidation: 0,
    id: "melvorF:AirGuard",
    areas: ["Air God Dungeon"],
  },
  {
    name: "Elementalist",
    attackStyle: "Magic",
    canStun: true,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 220,
    attackBonus: 9,
    spellMaxHit: 10.5,
    specialAttack: [
      {
        name: "Elemental Impact (Stun)",
        maxHitMultiplier: 100,
        fixedAttack: false,
      },
      {
        name: "Elemental Impact (Freeze)",
        maxHitMultiplier: 100,
        fixedAttack: false,
      },
      {
        name: "Elemental Impact (Burn)",
        maxHitMultiplier: 100,
        fixedAttack: false,
      },
      {
        name: "Elemental Impact (Frostburn)",
        maxHitMultiplier: 100,
        fixedAttack: false,
      },
    ],
    intimidation: 0,
    id: "melvorF:Elementalist",
    areas: ["Runic Ruins"],
  },
  {
    name: "Fearful Eye",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 220,
    attackBonus: 7,
    spellMaxHit: 10.5,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:FearfulEye",
    areas: ["Infernal Stronghold"],
  },
  {
    name: "Water Guard",
    attackStyle: "Magic",
    canStun: true,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 200,
    attackBonus: 26,
    spellMaxHit: 14.5,
    specialAttack: [
      { name: "Icy Chill", maxHit: 0, fixedAttack: true },
      { name: "Frozen Spears", maxHit: 20, fixedAttack: true },
    ],
    intimidation: 0,
    id: "melvorF:WaterGuard",
    areas: ["Water God Dungeon"],
  },
  {
    name: "Fire Guard",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 160,
    attackBonus: 70,
    specialAttack: [{ name: "Fireball", maxHit: 65, fixedAttack: true }],
    intimidation: 0,
    id: "melvorF:FireGuard",
    areas: ["Fire God Dungeon"],
  },
  {
    name: "The Kraken",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 100,
    attackBonus: 45,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:TheKraken",
    areas: ["Deep Sea Ship"],
  },
  {
    name: "Earth Guard",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 200,
    attackBonus: 29,
    specialAttack: [{ name: "Stone Wall", maxHit: 0, fixedAttack: true }],
    intimidation: 0,
    id: "melvorF:EarthGuard",
    areas: ["Earth God Dungeon"],
  },
  {
    name: "Miolite Monarch",
    attackStyle: "Magic",
    canStun: false,
    canSleep: true,
    usesNormalHit: true,
    attackLevel: 185,
    attackBonus: 36,
    spellMaxHit: 7,
    specialAttack: [{ name: "Drowsy Spores", maxHit: 20, fixedAttack: true }],
    intimidation: 0,
    id: "melvorF:MioliteMonarch",
    areas: ["Miolite Caves"],
  },
  {
    name: "Resurrected Eye",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 200,
    attackBonus: -12,
    spellMaxHit: 13.5,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:ResurrectedEye",
    areas: ["Volcanic Cave"],
  },
  {
    name: "Pegasus",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 160,
    attackBonus: 30,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:Pegasus",
    areas: ["High Lands"],
  },
  {
    name: "Protector of Ice",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 150,
    attackBonus: 0,
    specialAttack: [
      { name: "Frostburn", maxHitMultiplier: 100, fixedAttack: false },
    ],
    intimidation: 0,
    id: "melvorD:ProtectorofIce",
    areas: ["Frozen Cove"],
  },
  {
    name: "Vicious Serpent",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 260,
    attackBonus: 0,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:ViciousSerpent",
    areas: ["Volcanic Cave"],
  },
  {
    name: "Sand Beast",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 220,
    attackBonus: 5,
    specialAttack: [
      { name: "Greater Sandstorm", maxHitMultiplier: 15, fixedAttack: false },
    ],
    intimidation: 0,
    id: "melvorF:SandBeast",
    areas: ["Arid Plains"],
  },
  {
    name: "Noxious Serpent",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 235,
    attackBonus: 0,
    specialAttack: [{ name: "Poison Breath", maxHit: 15, fixedAttack: true }],
    intimidation: 0,
    id: "melvorF:NoxiousSerpent",
    areas: ["Toxic Swamps"],
  },
  {
    name: "Venomous Snake",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 180,
    attackBonus: 30,
    specialAttack: [{ name: "Toxic Bite", maxHit: 30, fixedAttack: true }],
    intimidation: 0,
    id: "melvorF:VenomousSnake",
    areas: ["Toxic Swamps"],
  },
  {
    name: "Giant Moth",
    attackStyle: "Magic",
    canStun: false,
    canSleep: true,
    usesNormalHit: true,
    attackLevel: 240,
    attackBonus: 20,
    spellMaxHit: 13,
    specialAttack: [{ name: "Noxious Powder", maxHit: 0, fixedAttack: true }],
    intimidation: 0,
    id: "melvorF:GiantMoth",
    areas: ["Toxic Swamps"],
  },
  {
    name: "Dark Horned Elite",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 178,
    attackBonus: 80,
    specialAttack: [{ name: "Ram", maxHitMultiplier: 100, fixedAttack: false }],
    intimidation: 0,
    id: "melvorF:DarkHornedElite",
    areas: ["Desolate Plains"],
  },
  {
    name: "Furious Horned Elite",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 250,
    attackBonus: 30,
    specialAttack: [
      { name: "Horn Shots", maxHitMultiplier: 60, fixedAttack: false },
    ],
    intimidation: 0,
    id: "melvorF:FuriousHornedElite",
    areas: ["Desolate Plains"],
  },
  {
    name: "Fire Spirit",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 380,
    attackBonus: 23,
    spellMaxHit: 9.5,
    specialAttack: [],
    intimidation: 0,
    id: "melvorD:FireSpirit",
    areas: ["Volcanic Cave"],
  },
  {
    name: "Red Devil",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 270,
    attackBonus: 5,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:RedDevil",
    areas: ["Infernal Stronghold"],
  },
  {
    name: "Fire Monster",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 280,
    attackBonus: 40,
    specialAttack: [{ name: "Burning Claws", maxHit: 40, fixedAttack: true }],
    intimidation: 0,
    id: "melvorF:FireMonster",
    areas: ["Fire God Dungeon"],
  },
  {
    name: "Air Monster",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 280,
    attackBonus: 30,
    specialAttack: [{ name: "Wind Blade", maxHit: 35, fixedAttack: true }],
    intimidation: 0,
    id: "melvorF:AirMonster",
    areas: ["Air God Dungeon"],
  },
  {
    name: "Water Monster",
    attackStyle: "Melee",
    canStun: true,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 280,
    attackBonus: 18,
    specialAttack: [
      { name: "Icy Chill", maxHit: 0, fixedAttack: true },
      { name: "Ice Break", maxHit: 36, fixedAttack: true },
    ],
    intimidation: 0,
    id: "melvorF:WaterMonster",
    areas: ["Water God Dungeon"],
  },
  {
    name: "Earth Monster",
    attackStyle: "Melee",
    canStun: true,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 280,
    attackBonus: 28,
    specialAttack: [{ name: "Charge", maxHit: 65, fixedAttack: true }],
    intimidation: 0,
    id: "melvorF:EarthMonster",
    areas: ["Earth God Dungeon"],
  },
  {
    name: "Elder Dragon",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 300,
    attackBonus: 30,
    specialAttack: [
      { name: "Burning Fireball", maxHit: 45, fixedAttack: true },
    ],
    intimidation: 0,
    id: "melvorF:ElderDragon",
    areas: ["Dragons Den"],
  },
  {
    name: "Rancora Spider",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 290,
    attackBonus: 20,
    specialAttack: [{ name: "Webshot", maxHit: 45, fixedAttack: true }],
    intimidation: 0,
    id: "melvorF:RancoraSpider",
    areas: ["Shrouded Badlands"],
  },
  {
    name: "Phoenix",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 350,
    attackBonus: 0,
    spellMaxHit: 13.5,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:Phoenix",
    areas: ["Infernal Stronghold"],
  },
  {
    name: "Elder Vampire",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 305,
    attackBonus: 0,
    specialAttack: [{ name: "Drain", maxHit: 30, fixedAttack: true }],
    intimidation: 0,
    id: "melvorF:ElderVampire",
    areas: ["Shrouded Badlands"],
  },
  {
    name: "Eye of Fear",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 260,
    attackBonus: 40,
    specialAttack: [],
    intimidation: 0,
    id: "melvorF:EyeOfFear",
    areas: ["Strange Cave"],
  },
  {
    name: "Cursed Maiden",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 330,
    attackBonus: 17,
    spellMaxHit: 14.5,
    specialAttack: [{ name: "Curse of Fear", maxHit: 60, fixedAttack: true }],
    intimidation: 0,
    id: "melvorF:CursedMaiden",
    areas: ["Shrouded Badlands"],
  },
  {
    name: "Bounty Hunter",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 230,
    attackBonus: 20,
    specialAttack: [{ name: "Hunter Expertise", maxHit: 0, fixedAttack: true }],
    intimidation: 0,
    id: "melvorF:BountyHunter",
    areas: ["Shrouded Badlands"],
  },
  {
    name: "Prat, the Protector of Secrets",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 480,
    attackBonus: 0,
    specialAttack: [
      { name: "Volley", maxHitMultiplier: 100, fixedAttack: false },
    ],
    intimidation: 0,
    id: "melvorD:PratTheProtectorOfSecrets",
    areas: ["Volcanic Cave"],
  },
  {
    name: "Hungry Plant",
    attackStyle: "Ranged",
    canStun: true,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 400,
    attackBonus: 15,
    specialAttack: [
      { name: "Bind", maxHit: 65, fixedAttack: true },
      { name: "Lure Trap", maxHit: 85, fixedAttack: true },
    ],
    intimidation: 10,
    id: "melvorTotH:HungryPlant",
    areas: ["Jungle Labyrinth", "Ancient Sanctuary"],
  },
  {
    name: "Wicked Greater Dragon",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 350,
    attackBonus: -1,
    spellMaxHit: 17.5,
    specialAttack: [
      { name: "Greater Dragonbreath", maxHit: 12, fixedAttack: true },
      { name: "Confusion", maxHitMultiplier: 75, fixedAttack: false },
    ],
    intimidation: 0,
    id: "melvorF:WickedGreaterDragon",
    areas: ["Perilous Peaks"],
  },
  {
    name: "Fire Golem",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 500,
    attackBonus: -6,
    spellMaxHit: 17.5,
    specialAttack: [{ name: "Scorching Ray", maxHit: 10, fixedAttack: true }],
    intimidation: 0,
    id: "melvorF:FireGolem",
    areas: ["Fire God Dungeon"],
  },
  {
    name: "Incendius",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 380,
    attackBonus: 5,
    specialAttack: [
      { name: "Burning Trail", maxHitMultiplier: 100, fixedAttack: false },
    ],
    intimidation: 0,
    id: "melvorF:Incendius",
    areas: ["Infernal Stronghold"],
  },
  {
    name: "Air Golem",
    attackStyle: "Ranged",
    canStun: true,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 520,
    attackBonus: 0,
    specialAttack: [{ name: "Whirlwind", maxHit: 55, fixedAttack: true }],
    intimidation: 0,
    id: "melvorF:AirGolem",
    areas: ["Air God Dungeon"],
  },
  {
    name: "Water Golem",
    attackStyle: "Magic",
    canStun: true,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 520,
    attackBonus: 8,
    spellMaxHit: 14.5,
    specialAttack: [{ name: "Flash Freeze", maxHit: 65, fixedAttack: true }],
    intimidation: 0,
    id: "melvorF:WaterGolem",
    areas: ["Water God Dungeon"],
  },
  {
    name: "Hunting Greater Dragon",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 395,
    attackBonus: 0,
    specialAttack: [
      { name: "Greater Dragonbreath", maxHit: 12, fixedAttack: true },
      { name: "Agility", maxHit: 65, fixedAttack: true },
    ],
    intimidation: 0,
    id: "melvorF:HuntingGreaterDragon",
    areas: ["Perilous Peaks"],
  },
  {
    name: "Earth Golem",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 380,
    attackBonus: 20,
    specialAttack: [{ name: "Boulder", maxHit: 85, fixedAttack: true }],
    intimidation: 0,
    id: "melvorF:EarthGolem",
    areas: ["Earth God Dungeon"],
  },
  {
    name: "Poison Toad",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 450,
    attackBonus: -32,
    spellMaxHit: 22.5,
    specialAttack: [{ name: "Poison Split", maxHit: 70, fixedAttack: true }],
    intimidation: 15,
    id: "melvorTotH:PoisonToad",
    areas: ["Jungle Labyrinth", "Ancient Sanctuary"],
  },
  {
    name: "Chaotic Greater Dragon",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 350,
    attackBonus: 20,
    specialAttack: [
      { name: "Greater Dragonbreath", maxHit: 12, fixedAttack: true },
      { name: "Chaotic Slam", maxHit: 65, fixedAttack: true },
    ],
    intimidation: 0,
    id: "melvorF:ChaoticGreaterDragon",
    areas: ["Perilous Peaks"],
  },
  {
    name: "Burning Snake",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 375,
    attackBonus: 20,
    specialAttack: [
      { name: "Poison Bite", maxHit: 85, fixedAttack: true },
      { name: "Smother", maxHit: 24, fixedAttack: true },
    ],
    intimidation: 9,
    id: "melvorTotH:BurningSnake",
    areas: ["Lava Lake", "Underground Lava Lake"],
  },
  {
    name: "Prat, the Guardian of Secrets",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 500,
    attackBonus: 0,
    specialAttack: [
      { name: "Volley", maxHitMultiplier: 100, fixedAttack: false },
      { name: "Infernal Volley", maxHitMultiplier: 100, fixedAttack: false },
    ],
    intimidation: 0,
    id: "melvorF:PratTheGuardianOfSecrets",
    areas: ["Infernal Stronghold"],
  },
  {
    name: "Scouter Spider",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 312,
    attackBonus: 23,
    specialAttack: [
      { name: "Web Trap", maxHit: 0, fixedAttack: true },
      { name: "Deadly Bite", maxHit: 90, fixedAttack: true },
    ],
    intimidation: 15,
    id: "melvorTotH:ScouterSpider",
    areas: [],
  },
  {
    name: "Lightning Spirit",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 500,
    attackBonus: -1,
    spellMaxHit: 17,
    specialAttack: [{ name: "Electric Ball", maxHit: 70, fixedAttack: true }],
    intimidation: 10,
    id: "melvorTotH:LightningSpirit",
    areas: ["Lightning Region"],
  },
  {
    name: "Murtia",
    attackStyle: "Melee",
    canStun: true,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 430,
    attackBonus: 0,
    specialAttack: [
      { name: "Icy Chill", maxHit: 0, fixedAttack: true },
      { name: "Winterland", maxHit: 0, fixedAttack: true },
    ],
    intimidation: 0,
    id: "melvorF:Murtia",
    areas: ["Water God Dungeon"],
  },
  {
    name: "Voltaire",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 670,
    attackBonus: 2,
    specialAttack: [{ name: "Tornado", maxHit: 40, fixedAttack: true }],
    intimidation: 0,
    id: "melvorF:Voltaire",
    areas: ["Air God Dungeon"],
  },
  {
    name: "Infernal Golem",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 450,
    attackBonus: 15,
    specialAttack: [
      { name: "Flame Barrage", maxHit: 75, fixedAttack: true },
      { name: "Smoldering Blow", maxHit: 100, fixedAttack: true },
    ],
    intimidation: 9,
    id: "melvorTotH:InfernalGolem",
    areas: ["Lava Lake", "Underground Lava Lake"],
  },
  {
    name: "Kongamato",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 475,
    attackBonus: 10,
    specialAttack: [
      { name: "Sharp Wing", maxHit: 80, fixedAttack: true },
      { name: "Ferocious Bite", maxHit: 100, fixedAttack: true },
    ],
    intimidation: 8,
    id: "melvorTotH:Kongamato",
    areas: ["Jungle Labyrinth", "Ancient Sanctuary"],
  },
  {
    name: "Umbora",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 450,
    attackBonus: 40,
    specialAttack: [
      { name: "Elusiveness", maxHit: 0, fixedAttack: true },
      { name: "Rapid Onslaught", maxHit: 95, fixedAttack: true },
    ],
    intimidation: 0,
    id: "melvorF:Umbora",
    areas: ["Dark Waters"],
  },
  {
    name: "Trapper Spider",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 379,
    attackBonus: 17,
    specialAttack: [
      { name: "Web Trap", maxHit: 0, fixedAttack: true },
      { name: "Deadly Bite", maxHit: 90, fixedAttack: true },
    ],
    intimidation: 20,
    id: "melvorTotH:TrapperSpider",
    areas: [],
  },
  {
    name: "Ophidia",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 525,
    attackBonus: 18,
    specialAttack: [{ name: "Grasping Roots", maxHit: 60, fixedAttack: true }],
    intimidation: 0,
    id: "melvorF:Ophidia",
    areas: ["Earth God Dungeon"],
  },
  {
    name: "Lissia",
    attackStyle: "Magic",
    canStun: true,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 500,
    attackBonus: 11,
    spellMaxHit: 18.5,
    specialAttack: [
      { name: "Icy Chill", maxHit: 0, fixedAttack: true },
      { name: "Winterland", maxHit: 0, fixedAttack: true },
    ],
    intimidation: 0,
    id: "melvorF:Lissia",
    areas: ["Water God Dungeon"],
  },
  {
    name: "Pyra",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 500,
    attackBonus: -1,
    spellMaxHit: 21.5,
    specialAttack: [{ name: "Meteor Shower", maxHit: 85, fixedAttack: true }],
    intimidation: 0,
    id: "melvorF:Pyra",
    areas: ["Fire God Dungeon"],
  },
  {
    name: "Aleron",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 500,
    attackBonus: 22,
    specialAttack: [{ name: "Tornado", maxHit: 40, fixedAttack: true }],
    intimidation: 0,
    id: "melvorF:Aleron",
    areas: ["Air God Dungeon"],
  },
  {
    name: "Rokken",
    attackStyle: "Ranged",
    canStun: true,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 600,
    attackBonus: 15,
    specialAttack: [
      { name: "Elusiveness", maxHit: 0, fixedAttack: true },
      { name: "Shockwave", maxHit: 97, fixedAttack: true },
    ],
    intimidation: 0,
    id: "melvorF:Rokken",
    areas: ["Dark Waters"],
  },
  {
    name: "Mistral",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 500,
    attackBonus: -3,
    spellMaxHit: 20,
    specialAttack: [{ name: "Grasping Roots", maxHit: 60, fixedAttack: true }],
    intimidation: 0,
    id: "melvorF:Mistral",
    areas: ["Earth God Dungeon"],
  },
  {
    name: "Ignis",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 530,
    attackBonus: 25,
    specialAttack: [{ name: "Meteor Shower", maxHit: 85, fixedAttack: true }],
    intimidation: 0,
    id: "melvorF:Ignis",
    areas: ["Fire God Dungeon"],
  },
  {
    name: "Ku-tul",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 650,
    attackBonus: -3,
    spellMaxHit: 18.5,
    specialAttack: [
      { name: "Elusiveness", maxHit: 0, fixedAttack: true },
      { name: "Curse of the Deep", maxHit: 99, fixedAttack: true },
    ],
    intimidation: 0,
    id: "melvorF:Kutul",
    areas: ["Dark Waters"],
  },
  {
    name: "Wicked Spider",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 426,
    attackBonus: -1,
    spellMaxHit: 21,
    specialAttack: [
      { name: "Web Trap", maxHit: 0, fixedAttack: true },
      { name: "Deadly Bite", maxHit: 90, fixedAttack: true },
    ],
    intimidation: 25,
    id: "melvorTotH:WickedSpider",
    areas: [],
  },
  {
    name: "Legaran Wurm",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 650,
    attackBonus: 0,
    specialAttack: [
      { name: "Burrow", maxHit: 72, fixedAttack: true },
      { name: "Penetrating Spike Shot", maxHit: 92, fixedAttack: true },
      { name: "Toxic Needles", maxHit: 62, fixedAttack: true },
    ],
    intimidation: 0,
    id: "melvorF:LegaranWurm",
    areas: ["Unhallowed Wasteland"],
  },
  {
    name: "Magic Fire Demon",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 600,
    attackBonus: 14,
    spellMaxHit: 17.5,
    specialAttack: [
      { name: "Lava Wave", maxHit: 75, fixedAttack: true },
      { name: "Explosion", maxHit: 98, fixedAttack: true },
    ],
    intimidation: 10,
    id: "melvorTotH:MagicFireDemon",
    areas: ["Lava Lake", "Underground Lava Lake"],
  },
  {
    name: "Frost Golem",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 600,
    attackBonus: 126,
    spellMaxHit: 10.5,
    specialAttack: [
      { name: "Chilling Winds", maxHit: 70, fixedAttack: true },
      { name: "Ice Shards", maxHit: 107, fixedAttack: true },
    ],
    intimidation: 7,
    id: "melvorTotH:FrostGolem",
    areas: ["Forsaken Tundra"],
  },
  {
    name: "Cursed Skeleton Warrior",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 600,
    attackBonus: 27,
    specialAttack: [
      { name: "Confusing Touch", maxHitMultiplier: 100, fixedAttack: false },
    ],
    intimidation: 38,
    id: "melvorTotH:CursedSkeletonWarrior",
    areas: ["Necromancers Palace"],
  },
  {
    name: "Cursed Lich",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 650,
    attackBonus: -6,
    spellMaxHit: 25.5,
    specialAttack: [
      { name: "Cursed Flames", maxHit: 90, fixedAttack: true },
      { name: "Cursed Frost Shards", maxHit: 70, fixedAttack: true },
      { name: "Cursed Tether", maxHit: 50, fixedAttack: true },
    ],
    intimidation: 0,
    id: "melvorF:CursedLich",
    areas: ["Unhallowed Wasteland"],
  },
  {
    name: "Conda",
    attackStyle: "Melee",
    canStun: true,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 525,
    attackBonus: 13,
    specialAttack: [
      { name: "Toxic Bite", maxHit: 30, fixedAttack: true },
      { name: "Deadly Wrap", maxHit: 24, fixedAttack: true },
    ],
    intimidation: 8,
    id: "melvorTotH:Conda",
    areas: ["Jungle Labyrinth", "Ancient Sanctuary"],
  },
  {
    name: "Malcs, the Guardian of Melvor",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 960,
    attackBonus: 0,
    specialAttack: [
      { name: "Razor-Sharp Claws", maxHit: 52, fixedAttack: true },
      { name: "Dragonbreath", maxHit: 6, fixedAttack: true },
    ],
    intimidation: 0,
    id: "melvorD:MalcsTheGuardianOfMelvor",
    areas: ["Volcanic Cave"],
  },
  {
    name: "Siren",
    attackStyle: "Magic",
    canStun: false,
    canSleep: true,
    usesNormalHit: true,
    attackLevel: 600,
    attackBonus: -12,
    spellMaxHit: 22.5,
    specialAttack: [
      { name: "Allure", maxHit: 0, fixedAttack: true },
      { name: "Drown", maxHit: 30, fixedAttack: true },
    ],
    intimidation: 8,
    id: "melvorTotH:Siren",
    areas: ["Foggy Lake"],
  },
  {
    name: "Basher Spider",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 469,
    attackBonus: 25,
    specialAttack: [
      { name: "Web Trap", maxHit: 0, fixedAttack: true },
      { name: "Deadly Bite", maxHit: 90, fixedAttack: true },
    ],
    intimidation: 30,
    id: "melvorTotH:BasherSpider",
    areas: [],
  },
  {
    name: "Malcs, the Leader of Dragons",
    attackStyle: "Melee",
    canStun: true,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 669,
    attackBonus: 0,
    specialAttack: [
      { name: "Tail Whip", maxHit: 69, fixedAttack: true },
      { name: "Penetrating Claws", maxHit: 64, fixedAttack: true },
      { name: "Inferno", maxHit: 20, fixedAttack: true },
      { name: "Sealing", maxHit: 0, fixedAttack: true },
    ],
    intimidation: 0,
    id: "melvorF:MalcsTheLeaderOfDragons",
    areas: ["Infernal Stronghold"],
  },
  {
    name: "Spiked Red Claw",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 500,
    attackBonus: 0,
    specialAttack: [
      { name: "Crushing Claws", maxHit: 85, fixedAttack: true },
      { name: "Cleave", maxHit: 70, fixedAttack: true },
      { name: "Savage Spike", maxHit: 100, fixedAttack: true },
    ],
    intimidation: 0,
    id: "melvorF:SpikedRedClaw",
    areas: ["Unhallowed Wasteland"],
  },
  {
    name: "Aeris",
    attackStyle: "Ranged",
    canStun: true,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 800,
    attackBonus: 2,
    specialAttack: [
      { name: "Barrage", maxHit: 10, fixedAttack: true },
      { name: "Wind Blade", maxHit: 35, fixedAttack: true },
      { name: "Whirlwind", maxHit: 55, fixedAttack: true },
      { name: "Tornado", maxHit: 40, fixedAttack: true },
      { name: "Cyclone", maxHit: 60, fixedAttack: true },
    ],
    intimidation: 0,
    id: "melvorF:Aeris",
    areas: ["Air God Dungeon"],
  },
  {
    name: "Greater Skeletal Dragon",
    attackStyle: "Melee",
    canStun: true,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 550,
    attackBonus: 0,
    specialAttack: [
      { name: "Bone Crush", maxHit: 75, fixedAttack: true },
      { name: "Spiked Tail Whip", maxHit: 50, fixedAttack: true },
      { name: "Desecration", maxHit: 0, fixedAttack: true },
    ],
    intimidation: 0,
    id: "melvorF:GreaterSkeletalDragon",
    areas: ["Unhallowed Wasteland"],
  },
  {
    name: "Enforcer Spider",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 538,
    attackBonus: 13,
    specialAttack: [
      { name: "Web Trap", maxHit: 0, fixedAttack: true },
      { name: "Deadly Bite", maxHit: 90, fixedAttack: true },
    ],
    intimidation: 30,
    id: "melvorTotH:EnforcerSpider",
    areas: [],
  },
  {
    name: "Alraune",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: true,
    usesNormalHit: false,
    attackLevel: 700,
    attackBonus: 15,
    specialAttack: [
      { name: "Efflorescence", maxHit: 0, fixedAttack: true },
      { name: "Thorned Roots", maxHit: 75, fixedAttack: true },
      { name: "Razor Wind", maxHit: 93, fixedAttack: true },
    ],
    intimidation: 9,
    id: "melvorTotH:Alraune",
    areas: ["Jungle Labyrinth", "Ancient Sanctuary"],
  },
  {
    name: "Glacia",
    attackStyle: "Magic",
    canStun: true,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 600,
    attackBonus: 5,
    spellMaxHit: 18.5,
    specialAttack: [
      { name: "Frozen Spears", maxHit: 20, fixedAttack: true },
      { name: "Ice Break", maxHit: 36, fixedAttack: true },
      { name: "Flash Freeze", maxHit: 65, fixedAttack: true },
      { name: "Winterland", maxHit: 0, fixedAttack: true },
      { name: "Frigid Waves", maxHit: 78, fixedAttack: true },
    ],
    intimidation: 0,
    id: "melvorF:Glacia",
    areas: ["Water God Dungeon"],
  },
  {
    name: "Manticore",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 650,
    attackBonus: 19,
    specialAttack: [
      { name: "Flame Rush", maxHit: 80, fixedAttack: true },
      { name: "Fatal Spike", maxHit: 93, fixedAttack: true },
    ],
    intimidation: 16,
    id: "melvorTotH:Manticore",
    areas: ["Lava Lake", "Underground Lava Lake"],
  },
  {
    name: "Polar Bear",
    attackStyle: "Melee",
    canStun: true,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 650,
    attackBonus: 16,
    specialAttack: [{ name: "Freezing Roar", maxHit: 77, fixedAttack: true }],
    intimidation: 15,
    id: "melvorTotH:PolarBear",
    areas: ["Forsaken Tundra"],
  },
  {
    name: "Terran",
    attackStyle: "Melee",
    canStun: true,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 570,
    attackBonus: 0,
    specialAttack: [
      { name: "Stone Wall", maxHit: 0, fixedAttack: true },
      { name: "Charge", maxHit: 65, fixedAttack: true },
      { name: "Boulder", maxHit: 85, fixedAttack: true },
      { name: "Grasping Roots", maxHit: 60, fixedAttack: true },
      { name: "Seismic Slam", maxHit: 95, fixedAttack: true },
    ],
    intimidation: 0,
    id: "melvorF:Terran",
    areas: ["Earth God Dungeon"],
  },
  {
    name: "Ragnar",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 400,
    attackBonus: 4,
    spellMaxHit: 25.5,
    specialAttack: [
      { name: "Fireball", maxHit: 65, fixedAttack: true },
      { name: "Burning Claws", maxHit: 40, fixedAttack: true },
      { name: "Scorching Ray", maxHit: 10, fixedAttack: true },
      { name: "Meteor Shower", maxHit: 85, fixedAttack: true },
      { name: "Cataclysm", maxHit: 130, fixedAttack: true },
    ],
    intimidation: 0,
    id: "melvorF:Ragnar",
    areas: ["Fire God Dungeon"],
  },
  {
    name: "Spectral Ice Wolf",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 750,
    attackBonus: -9,
    spellMaxHit: 18.5,
    specialAttack: [
      { name: "Spectral Clones", maxHitMultiplier: 150, fixedAttack: false },
    ],
    intimidation: 19,
    id: "melvorTotH:SpectralIceWolf",
    areas: ["Forsaken Tundra"],
  },
  {
    name: "Lightning Monkey",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 650,
    attackBonus: 16,
    specialAttack: [
      { name: "Rapid Static Strikes", maxHit: 65, fixedAttack: true },
      { name: "Focused Static Punch", maxHit: 90, fixedAttack: true },
    ],
    intimidation: 10,
    id: "melvorTotH:LightningMonkey",
    areas: ["Lightning Region"],
  },
  {
    name: "Guardian Spider",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 594,
    attackBonus: 25,
    spellMaxHit: 21,
    specialAttack: [
      { name: "Web Trap", maxHit: 0, fixedAttack: true },
      { name: "Deadly Bite", maxHit: 90, fixedAttack: true },
    ],
    intimidation: 30,
    id: "melvorTotH:GuardianSpider",
    areas: [],
  },
  {
    name: "Plague Doctor",
    attackStyle: "Magic",
    canStun: false,
    canSleep: true,
    usesNormalHit: true,
    attackLevel: 900,
    attackBonus: -46,
    spellMaxHit: 20,
    specialAttack: [
      { name: "Harmful Concoction", maxHit: 20, fixedAttack: true },
      { name: "Disease Swarm", maxHit: 10.5, fixedAttack: true },
    ],
    intimidation: 40,
    id: "melvorTotH:PlagueDoctor",
    areas: ["Afflicted City"],
  },
  {
    name: "Lightning Golem",
    attackStyle: "Ranged",
    canStun: true,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 800,
    attackBonus: 0,
    specialAttack: [{ name: "Shock Blast", maxHit: 94, fixedAttack: true }],
    intimidation: 11,
    id: "melvorTotH:LightningGolem",
    areas: ["Lightning Region"],
  },
  {
    name: "Large Ice Troll",
    attackStyle: "Melee",
    canStun: true,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 750,
    attackBonus: 30,
    specialAttack: [
      { name: "Frozen Club", maxHit: 80, fixedAttack: true },
      { name: "Rolling Snowball", maxHit: 90, fixedAttack: true },
    ],
    intimidation: 4,
    id: "melvorTotH:LargeIceTroll",
    areas: ["Forsaken Tundra"],
  },
  {
    name: "Cockatrice",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 800,
    attackBonus: 15,
    specialAttack: [
      { name: "Life Drain", maxHit: 80, fixedAttack: true },
      { name: "Decaying Shots", maxHit: 125, fixedAttack: true },
    ],
    intimidation: 27,
    id: "melvorTotH:Cockatrice",
    areas: ["Afflicted City"],
  },
  {
    name: "Tree Giant",
    attackStyle: "Melee",
    canStun: true,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 650,
    attackBonus: 22,
    specialAttack: [
      { name: "Entangle", maxHit: 80, fixedAttack: true },
      { name: "Tree Slam", maxHit: 100, fixedAttack: true },
    ],
    intimidation: 29,
    id: "melvorTotH:TreeGiant",
    areas: ["Cursed Forest"],
  },
  {
    name: "Tree Spirit",
    attackStyle: "Magic",
    canStun: false,
    canSleep: true,
    usesNormalHit: true,
    attackLevel: 800,
    attackBonus: -30,
    spellMaxHit: 20,
    specialAttack: [
      { name: "Curse of Madness", maxHit: 70, fixedAttack: true },
      { name: "Silence of the Forest", maxHit: 0, fixedAttack: true },
    ],
    intimidation: 38,
    id: "melvorTotH:TreeSpirit",
    areas: ["Cursed Forest"],
  },
  {
    name: "Shadow Beast",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 700,
    attackBonus: -7,
    specialAttack: [
      { name: "Surrounded", maxHitMultiplier: 100, fixedAttack: false },
      { name: "Shadow Bite", maxHitMultiplier: 150, fixedAttack: false },
    ],
    intimidation: 24,
    id: "melvorTotH:ShadowBeast",
    areas: ["Afflicted City"],
  },
  {
    name: "Gret-Yun",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 700,
    attackBonus: 19,
    specialAttack: [
      { name: "Greater Fireball", maxHit: 82, fixedAttack: true },
      { name: "Headbutt", maxHit: 85, fixedAttack: true },
      { name: "Master of Heat", maxHit: 0, fixedAttack: true },
    ],
    intimidation: 20,
    id: "melvorTotH:GretYun",
    areas: ["Lava Lake", "Underground Lava Lake"],
  },
  {
    name: "Monster Croc",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 800,
    attackBonus: 11,
    specialAttack: [
      { name: "Predator", maxHit: 0, fixedAttack: true },
      { name: "Crushing Jaws", maxHitMultiplier: 100, fixedAttack: false },
    ],
    intimidation: 19,
    id: "melvorTotH:MonsterCroc",
    areas: ["Foggy Lake"],
  },
  {
    name: "Phantom",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 1000,
    attackBonus: -7,
    specialAttack: [
      { name: "Ethereal Shots", maxHitMultiplier: 100, fixedAttack: false },
      { name: "Weakening Shot", maxHitMultiplier: 100, fixedAttack: false },
    ],
    intimidation: 43,
    id: "melvorTotH:Phantom",
    areas: ["Midnight Valley"],
  },
  {
    name: "Banshee",
    attackStyle: "Magic",
    canStun: false,
    canSleep: true,
    usesNormalHit: true,
    attackLevel: 1000,
    attackBonus: -51,
    spellMaxHit: 25.5,
    specialAttack: [
      { name: "Ghostly Terror", maxHitMultiplier: 100, fixedAttack: false },
      { name: "Blinding Fear", maxHitMultiplier: 100, fixedAttack: false },
    ],
    intimidation: 43,
    id: "melvorTotH:Banshee",
    areas: ["Midnight Valley"],
  },
  {
    name: "Bel-Noth",
    attackStyle: "Magic",
    canStun: true,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 950,
    attackBonus: 13,
    spellMaxHit: 14.5,
    specialAttack: [
      { name: "Blinding Beams", maxHit: 50, fixedAttack: true },
      { name: "Petrifying Glare", maxHitMultiplier: 110, fixedAttack: false },
    ],
    intimidation: 36,
    id: "melvorTotH:Beholder",
    areas: ["Necromancers Palace"],
  },
  {
    name: "Morellia",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 850,
    attackBonus: 30,
    specialAttack: [
      { name: "Poison Bulbs", maxHit: 70, fixedAttack: true },
      { name: "Thorned Roots", maxHit: 75, fixedAttack: true },
      { name: "Seeking Roots", maxHit: 100, fixedAttack: true },
      { name: "Full Bloom", maxHit: 52, fixedAttack: true },
    ],
    intimidation: 21,
    id: "melvorTotH:Morellia",
    areas: ["Ancient Sanctuary"],
  },
  {
    name: "Leviathan",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 600,
    attackBonus: 13,
    specialAttack: [
      { name: "Spikes from Below", maxHit: 80, fixedAttack: true },
      { name: "Spiked Slam", maxHitMultiplier: 100, fixedAttack: false },
    ],
    intimidation: 23,
    id: "melvorTotH:Leviathan",
    areas: ["Foggy Lake"],
  },
  {
    name: "Spectre",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 758,
    attackBonus: 0,
    specialAttack: [
      { name: "Curse Of Torment", maxHit: 70, fixedAttack: true },
      { name: "Spinning Axe", maxHitMultiplier: 50, fixedAttack: false },
    ],
    intimidation: 43,
    id: "melvorTotH:Spectre",
    areas: ["Midnight Valley"],
  },
  {
    name: "Goliath Werewolf",
    attackStyle: "Melee",
    canStun: true,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 700,
    attackBonus: 18,
    specialAttack: [
      { name: "Crushing Smash", maxHitMultiplier: 110, fixedAttack: false },
    ],
    intimidation: 35,
    id: "melvorTotH:GoliathWerewolf",
    areas: ["Afflicted City"],
  },
  {
    name: "Ice Hydra",
    attackStyle: "Magic",
    canStun: true,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 775,
    attackBonus: 55,
    spellMaxHit: 14.5,
    specialAttack: [
      { name: "Ice Blast", maxHit: 95, fixedAttack: true },
      { name: "Freezing Breath", maxHit: 160, fixedAttack: true },
      { name: "Ice Reanimation", maxHit: 0, fixedAttack: true },
    ],
    intimidation: 20,
    id: "melvorTotH:IceHydra",
    areas: ["Forsaken Tundra"],
  },
  {
    name: "Cursed Spirit",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 1000,
    attackBonus: -46,
    spellMaxHit: 21.5,
    specialAttack: [
      { name: "Curse Of Torment", maxHit: 70, fixedAttack: true },
      { name: "Soulburn", maxHit: 86, fixedAttack: true },
    ],
    intimidation: 38,
    id: "melvorTotH:CursedSpirit",
    areas: ["Cursed Forest"],
  },
  {
    name: "Twin Sea Dragon Serpent",
    attackStyle: "Ranged",
    canStun: false,
    canSleep: true,
    usesNormalHit: false,
    attackLevel: 900,
    attackBonus: -9,
    specialAttack: [
      { name: "Water Dance", maxHit: 0, fixedAttack: true },
      { name: "Torrential Dragonbreath", maxHit: 30, fixedAttack: true },
      { name: "Giant Bubble", maxHit: 80, fixedAttack: true },
      { name: "Tsunami", maxHit: 80, fixedAttack: true },
    ],
    intimidation: 29,
    id: "melvorTotH:TwinSeaDragonSerpent",
    areas: ["Foggy Lake"],
  },
  // TODO: Handle spider queen
  // {
  //   name: "Spider Queen",
  //   canStun: false,
  //   canSleep: false,
  //   attackStyle: null,
  //   usesNormalHit: false,
  //   specialAttack: [
  //     { name: "Web Trap", maxHit: 0, fixedAttack: true },
  //     { name: "Sharp Slice", maxHit: 80, fixedAttack: true },
  //     { name: "Fatal Bite", maxHit: 130, fixedAttack: true },
  //     { name: "Caught in the Web", maxHit: 0, fixedAttack: true },
  //   ],
  //   intimidation: 36,
  //   id: "melvorTotH:SpiderQueen",
  //   areas: ["Lair of the Spider Queen"],
  // },
  {
    name: "RaZu, Lord of the Skies",
    attackStyle: "Magic",
    canStun: true,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 950,
    attackBonus: -24,
    spellMaxHit: 21,
    specialAttack: [
      { name: "Lightning Strike", maxHit: 85, fixedAttack: true },
      { name: "Electric Charge", maxHit: 0, fixedAttack: true },
      { name: "Lightning Breath", maxHit: 48, fixedAttack: true },
      { name: "Thunderbolt", maxHit: 92, fixedAttack: true },
    ],
    intimidation: 13,
    id: "melvorTotH:RaZu",
    areas: ["Lightning Region"],
  },
  {
    name: "Trogark",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 750,
    attackBonus: 22,
    specialAttack: [
      { name: "Mega Fireball", maxHit: 100, fixedAttack: true },
      { name: "Burning Fury", maxHit: 105, fixedAttack: true },
      { name: "Ward of Flame", maxHit: 0, fixedAttack: true },
      { name: "Unleashed Power", maxHit: 54, fixedAttack: true },
    ],
    intimidation: 20,
    id: "melvorTotH:Trogark",
    areas: ["Underground Lava Lake"],
  },
  {
    name: "Dark Knight",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 878,
    attackBonus: -20,
    specialAttack: [
      { name: "Blade Shadow", maxHitMultiplier: 110, fixedAttack: false },
      { name: "Dark Blade", maxHitMultiplier: 50, fixedAttack: false },
    ],
    intimidation: 42,
    id: "melvorTotH:DarkKnight",
    areas: ["Necromancers Palace"],
  },
  {
    name: "Lady Darkheart",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 1000,
    attackBonus: -48,
    spellMaxHit: 22.5,
    specialAttack: [
      { name: "Curse of Madness", maxHit: 70, fixedAttack: true },
      { name: "Curse Of Torment", maxHit: 70, fixedAttack: true },
      { name: "Curse of Despair", maxHit: 70, fixedAttack: true },
      { name: "Devourer of the Cursed", maxHit: 44, fixedAttack: true },
    ],
    intimidation: 29,
    id: "melvorTotH:LadyDarkheart",
    areas: ["Cursed Forest"],
  },
  {
    name: "Fiozor, the Ancient Necromancer",
    attackStyle: "Magic",
    canStun: false,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 1050,
    attackBonus: -20,
    spellMaxHit: 24,
    specialAttack: [
      { name: "Shade Summon", maxHitMultiplier: 100, fixedAttack: false },
      {
        name: "Greater Shade Summon",
        maxHitMultiplier: 100,
        fixedAttack: false,
      },
      { name: "Phantom Summon", maxHitMultiplier: 100, fixedAttack: false },
      { name: "Curse Totem Summon", maxHitMultiplier: 100, fixedAttack: false },
    ],
    intimidation: 36,
    id: "melvorTotH:Fiozor",
    areas: ["Necromancers Palace"],
  },
  {
    name: "Arctair",
    attackStyle: "Ranged",
    canStun: true,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 1090,
    attackBonus: -40,
    specialAttack: [
      { name: "Feather Storm", maxHitMultiplier: 300, fixedAttack: false },
      { name: "Feather Barrier", maxHit: 0, fixedAttack: true },
      { name: "Feather Lance", maxHit: 100, fixedAttack: true },
    ],
    intimidation: 39,
    id: "melvorTotH:Arctair",
    areas: ["Golden Cloud Mountains"],
  },
  {
    name: "Harkair",
    attackStyle: "Magic",
    canStun: true,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 1100,
    attackBonus: -56,
    spellMaxHit: 22.5,
    specialAttack: [
      { name: "Slicing Maelstrom", maxHitMultiplier: 125, fixedAttack: false },
      { name: "Wind Barrier", maxHit: 0, fixedAttack: true },
      { name: "Feather Tornado", maxHit: 75, fixedAttack: true },
    ],
    intimidation: 39,
    id: "melvorTotH:Harkair",
    areas: ["Golden Cloud Mountains"],
  },
  {
    name: "Torvair",
    attackStyle: "Melee",
    canStun: true,
    canSleep: false,
    usesNormalHit: true,
    attackLevel: 808,
    attackBonus: -31,
    specialAttack: [
      { name: "Agile Wings", maxHitMultiplier: 300, fixedAttack: false },
      { name: "Rapid Parry", maxHitMultiplier: 100, fixedAttack: false },
      { name: "Full Charge", maxHit: 80, fixedAttack: true },
    ],
    intimidation: 39,
    id: "melvorTotH:Torvair",
    areas: ["Golden Cloud Mountains"],
  },
  {
    name: "Vorloran Devastator",
    attackStyle: "Magic",
    canStun: true,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 1200,
    attackBonus: -33,
    spellMaxHit: 25.5,
    specialAttack: [
      { name: "Frostbite", maxHit: 75, fixedAttack: true },
      { name: "Quake", maxHit: 54, fixedAttack: true },
      { name: "Magic Ray", maxHitMultiplier: 70, fixedAttack: false },
      { name: "Ocean Song", maxHit: 135, fixedAttack: true },
    ],
    intimidation: 40,
    id: "melvorTotH:VorloranDevastator",
    areas: ["Millennium Gate"],
  },
  {
    name: "Vorloran Watcher",
    attackStyle: "Ranged",
    canStun: true,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 1200,
    attackBonus: -34,
    specialAttack: [
      { name: "Poisoned Hit", maxHitMultiplier: 90, fixedAttack: false },
      { name: "Piercing Arrow", maxHitMultiplier: 200, fixedAttack: false },
      { name: "Impairing Shot", maxHitMultiplier: 100, fixedAttack: false },
      { name: "Shockwave", maxHit: 97, fixedAttack: true },
    ],
    intimidation: 40,
    id: "melvorTotH:VorloranWatcher",
    areas: ["Millennium Gate"],
  },
  {
    name: "Vorloran Protector",
    attackStyle: "Melee",
    canStun: false,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 888,
    attackBonus: -24,
    specialAttack: [
      { name: "Deadly Cut", maxHitMultiplier: 100, fixedAttack: false },
      { name: "Flurry", maxHitMultiplier: 50, fixedAttack: false },
      { name: "Infernum", maxHitMultiplier: 175, fixedAttack: false },
      { name: "Tidal Wave", maxHitMultiplier: 35, fixedAttack: false },
    ],
    intimidation: 40,
    id: "melvorTotH:VorloranProtector",
    areas: ["Millennium Gate"],
  },
  {
    name: "Guardian of the Herald",
    attackStyle: "Melee",
    canStun: true,
    canSleep: false,
    usesNormalHit: false,
    attackLevel: 1204,
    attackBonus: 6,
    specialAttack: [
      {
        name: "Aggressive Onslaught",
        maxHitMultiplier: 100,
        fixedAttack: false,
      },
      { name: "Battlecry", maxHit: 0, fixedAttack: true },
      { name: "Unstoppable Force", maxHit: 100, fixedAttack: true },
      { name: "Sunder", maxHit: 125, fixedAttack: true },
    ],
    intimidation: 40,
    id: "melvorTotH:GuardianoftheHerald",
    areas: ["Millennium Gate"],
  },
] as const;

export const slayerAreas = [
  {
    name: "Penumbra",
    monsters: [
      "Mummy",
      "Statue",
      "Stone Snake",
      "Undead Werewolf",
      "Vampire",
      "Fierce Devil",
    ],
  },
  {
    name: "Forest of Goo",
    monsters: [
      "Goo Monster",
      "Green Goo Monster",
      "Purple Goo Monster",
      "Scattered Goo Monster",
    ],
  },
  {
    name: "Strange Cave",
    monsters: [
      "Lots of Eyes",
      "Many Eyed Monster",
      "Strange Eyed Monster",
      "Eyes",
      "Superior Eyed Monster",
      "Eye of Fear",
    ],
  },
  {
    name: "Holy Isles",
    monsters: [
      "Fairy",
      "Valkyrie",
      "Angel",
      "Holy Archer",
      "Paladin",
      "Priest",
    ],
  },
  {
    name: "Runic Ruins",
    monsters: ["Druid", "Thief", "Shaman", "Necromancer", "Elementalist"],
  },
  {
    name: "Arid Plains",
    monsters: [
      "Turkul Riders",
      "Turkul Archers",
      "Turkul Throwers",
      "Turkul Giant",
      "Turkul General",
      "Sand Beast",
    ],
  },
  { name: "High Lands", monsters: ["Griffin", "Pegasus"] },
  {
    name: "Toxic Swamps",
    monsters: ["Noxious Serpent", "Venomous Snake", "Giant Moth"],
  },
  {
    name: "Desolate Plains",
    monsters: [
      "Raging Horned Elite",
      "Seething Horned Elite",
      "Dark Horned Elite",
      "Furious Horned Elite",
    ],
  },
  {
    name: "Shrouded Badlands",
    monsters: [
      "Rancora Spider",
      "Elder Vampire",
      "Cursed Maiden",
      "Bounty Hunter",
    ],
  },
  {
    name: "Perilous Peaks",
    monsters: [
      "Wicked Greater Dragon",
      "Hunting Greater Dragon",
      "Chaotic Greater Dragon",
    ],
  },
  { name: "Dark Waters", monsters: ["Umbora", "Rokken", "Ku-tul"] },
  {
    name: "Unhallowed Wasteland",
    monsters: [
      "Legaran Wurm",
      "Cursed Lich",
      "Spiked Red Claw",
      "Greater Skeletal Dragon",
    ],
  },
  {
    name: "Jungle Labyrinth",
    monsters: ["Hungry Plant", "Poison Toad", "Kongamato", "Conda", "Alraune"],
  },
  {
    name: "Lava Lake",
    monsters: [
      "Burning Snake",
      "Infernal Golem",
      "Magic Fire Demon",
      "Manticore",
      "Gret-Yun",
    ],
  },
  {
    name: "Forsaken Tundra",
    monsters: [
      "Large Ice Troll",
      "Frost Golem",
      "Polar Bear",
      "Spectral Ice Wolf",
      "Ice Hydra",
    ],
  },
  {
    name: "Foggy Lake",
    monsters: ["Siren", "Monster Croc", "Leviathan", "Twin Sea Dragon Serpent"],
  },
  {
    name: "Afflicted City",
    monsters: [
      "Shadow Beast",
      "Plague Doctor",
      "Cockatrice",
      "Goliath Werewolf",
    ],
  },
  { name: "Midnight Valley", monsters: ["Phantom", "Banshee", "Spectre"] },
  {
    name: "Golden Cloud Mountains",
    monsters: ["Torvair", "Arctair", "Harkair"],
  },
  {
    name: "Millennium Gate",
    monsters: [
      "Vorloran Devastator",
      "Vorloran Watcher",
      "Vorloran Protector",
      "Guardian of the Herald",
    ],
  },
] as const;
